# Generated by Django 3.0.8 on 2020-09-05 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import itrac.models.project


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coded_id', models.CharField(max_length=40, null=True)),
                ('issue_type', models.CharField(choices=[('01', 'Break/fix'), ('02', 'New feature'), ('03', 'Optimization'), ('04', 'Task')], default='01', max_length=2)),
                ('status', models.CharField(choices=[('01', 'Open'), ('02', 'Investigate'), ('03', 'Await approval'), ('04', 'Build in progress'), ('05', 'Validate in progress'), ('06', 'Complete'), ('07', 'Closed')], default='01', max_length=2)),
                ('priority', models.CharField(choices=[('1', '1 - highest'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - lowest')], max_length=1, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('slug', models.CharField(blank=True, max_length=250)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('resolution_details', models.CharField(blank=True, max_length=250, null=True)),
                ('upvotes', models.IntegerField(default=0, verbose_name='likes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignee', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SavedIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_savedissue', to='itrac.Issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_savedissues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(default='WINN', max_length=20)),
                ('slug', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=40, null=True)),
                ('URL', models.CharField(max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, upload_to=itrac.models.project.get_avatar_full_path)),
                ('avatar_version', models.IntegerField(blank=True, default=0, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='IssueToIssueLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_from_type', models.CharField(choices=[('01', 'relates to'), ('02', 'blocks'), ('03', 'is blocked by'), ('04', 'causes'), ('05', 'is caused by'), ('06', 'clones'), ('07', 'is cloned by'), ('08', 'duplicates'), ('09', 'is duplicated by')], default='01', max_length=2)),
                ('link_to_type', models.CharField(choices=[('01', 'relates to'), ('02', 'blocks'), ('03', 'is blocked by'), ('04', 'causes'), ('05', 'is caused by'), ('06', 'clones'), ('07', 'is cloned by'), ('08', 'duplicates'), ('09', 'is duplicated by')], default='01', max_length=2)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('linked_from_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to_issues', to='itrac.Issue')),
                ('linked_to_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_from_issues', to='itrac.Issue')),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'itrac_issue_issue_link',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='itrac.Project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='issues', to='itrac.Tag'),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_issue', to='itrac.Issue')),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['title'], name='itrac_tag_title_c88491_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title'], name='itrac_proje_title_8071b7_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['title'], name='itrac_issue_title_8c63b4_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['coded_id'], name='itrac_issue_coded_i_2094ef_idx'),
        ),
    ]
